# -*- coding: utf-8 -*-
"""Bank Marketing Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDBlja5hUBkK3mFlEK3D04F92pEJaNea
"""

!pip install ucimlrepo

# fetch dataset
bank_marketing = fetch_ucirepo(id=222)

# data (as pandas dataframes)
X = bank_marketing.data.features
y = bank_marketing.data.targets

# metadata
print(bank_marketing.metadata)

# variable information
print(bank_marketing.variables)

# ===========================================
# 📊 ANALYSE EXPLORATOIRE DU DATASET BANK MARKETING
# ===========================================

# === 1. IMPORT DES LIBRAIRIES ===
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# (si seaborn n'est pas installé)
# !pip install seaborn

# === 2. CHARGEMENT DU DATASET ===
from ucimlrepo import fetch_ucirepo

bank_marketing = fetch_ucirepo(id=222)
X = bank_marketing.data.features
y = bank_marketing.data.targets

# Fusion des features et de la variable cible
data = pd.concat([X, y], axis=1)

# === 3. APERÇU DU DATASET ===
print("\n===== Aperçu des données =====")
display(data.head())
print("\nDimensions :", data.shape)
print("\nColonnes :", list(data.columns))

# === 4. INFORMATIONS GÉNÉRALES ===
print("\n===== Informations générales =====")
data.info()

print("\n===== Statistiques descriptives =====")
display(data.describe(include='all').T)

# === 5. VALEURS MANQUANTES ===
print("\n===== Valeurs manquantes =====")
display(data.isnull().sum())

# === 6. DISTRIBUTION DE LA VARIABLE CIBLE ===
target_col = y.columns[0]
plt.figure(figsize=(5, 4))
sns.countplot(x=target_col, hue=target_col, data=data, palette="Set2", legend=False)
plt.title("Répartition de la variable cible (Souscription à un dépôt à terme)")
plt.xlabel("Souscription (Oui / Non)")
plt.ylabel("Nombre de clients")
plt.show()

# === 7. DISTRIBUTIONS DE QUELQUES VARIABLES NUMÉRIQUES ===
numeric_cols = data.select_dtypes(include=np.number).columns

data[numeric_cols].hist(bins=20, figsize=(12, 8), color="skyblue", edgecolor="black")
plt.suptitle("Distribution des variables numériques", fontsize=14)
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent suptitle overlap
plt.show()

# === 8. CORRÉLATIONS ENTRE VARIABLES NUMÉRIQUES ===
plt.figure(figsize=(10, 8))
sns.heatmap(data[numeric_cols].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matrice de corrélation des variables numériques")
plt.show()

# === 9. ANALYSE CROISÉE : TAUX DE SOUSCRIPTION PAR CATÉGORIE ===
cat_cols = data.select_dtypes(exclude=np.number).columns

for col in cat_cols[:5]:  # on limite à 5 pour éviter trop de graphiques
    plt.figure(figsize=(6, 4))
    sns.countplot(x=col, hue=target_col, data=data, palette="pastel")
    plt.title(f"Taux de souscription par {col}")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# === 10. ANALYSE DU TAUX DE SOUSCRIPTION SELON L’ÂGE ===
plt.figure(figsize=(8, 5))
sns.boxplot(x=target_col, y='age', hue=target_col, data=data, palette="Set3", legend=False)
plt.title("Distribution de l'âge selon la souscription")
plt.xlabel("Souscription (Oui / Non)")
plt.ylabel("Âge")
plt.show()

# === 11. INTERPRÉTATION RAPIDE ===
print("\n===== Interprétation générale =====")
print("""
1️⃣ La variable cible est souvent déséquilibrée (plus de 'non' que de 'oui').
2️⃣ L’âge, le solde moyen et le nombre de contacts influencent la probabilité de souscription.
3️⃣ Certaines professions et niveaux d’éducation montrent des taux de souscription plus élevés.
4️⃣ Les campagnes précédentes (pdays, previous, poutcome) ont un fort impact.
5️⃣ Les relations entre variables numériques sont modérées, sauf entre celles liées à la durée d'appel et au succès.
""")